[tool.poetry]
name = "data-security-ufabc"
version = "0.1.0"
description = ""
authors = ["Diogo Miyake <akio.miyake@live.com>"]

[tool.poetry.dependencies]
python = "^3.9"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
